export const procurementDocumentSchema = {
  type: "object",
  properties: {
    document_type_detected: { type: "string" },
    is_document_type_match: { type: "boolean" },
    extraction_status: {
      type: "string",
      enum: ["SUCCESS", "PARTIAL", "FAILED"]
    },
    fields: {
      type: "object",
      properties: {
        classified_document_type: { type: ["string", "null"] },
        document_number: { type: ["string", "null"] },
        document_number_source: { type: ["string", "null"] },
        document_date: { type: ["string", "null"] },
        document_date_source: { type: ["string", "null"] },
        purchase_order_number: { type: ["string", "null"] },
        purchase_order_number_source: { type: ["string", "null"] },
        purchase_order_numbers: {
          type: "array",
          items: { type: "string" }
        },
        supplier_name: { type: ["string", "null"] },
        supplier_registration_number: { type: ["string", "null"] },
        supplier_vat_number: { type: ["string", "null"] },
        supplier_vat_number_source: { type: ["string", "null"] },
        supplier_is_vat_vendor: { type: ["boolean", "null"] },
        supplier_country: { type: ["string", "null"] },
        customer_name: { type: ["string", "null"] },
        customer_registration_number: { type: ["string", "null"] },
        customer_vat_number: { type: ["string", "null"] },
        customer_vat_number_source: { type: ["string", "null"] },
        customer_country: { type: ["string", "null"] },
        currency: { type: ["string", "null"] },
        subtotal: { type: ["number", "null"] },
        discount_total: { type: ["number", "null"] },
        tax_total: { type: ["number", "null"] },
        shipping_total: { type: ["number", "null"] },
        other_charges_total: { type: ["number", "null"] },
        total_amount: { type: ["number", "null"] },
        received_by: { type: ["string", "null"] },
        received_date: { type: ["string", "null"] },
        signature_present: { type: ["boolean", "null"] },
        stamp_present: { type: ["boolean", "null"] },
        line_items: {
          type: "array",
          items: {
            type: "object",
            properties: {
              line_number: { type: ["string", "null"] },
              item_code: { type: ["string", "null"] },
              description: { type: ["string", "null"] },
              quantity: { type: ["number", "null"] },
              unit_of_measure: { type: ["string", "null"] },
              unit_price: { type: ["number", "null"] },
              discount_percentage: { type: ["number", "null"] },
              discount_amount: { type: ["number", "null"] },
              tax_rate: { type: ["number", "null"] },
              tax_amount: { type: ["number", "null"] },
              line_subtotal: { type: ["number", "null"] },
              line_total: { type: ["number", "null"] },
              purchase_order_number: { type: ["string", "null"] },
              purchase_order_line_number: { type: ["string", "null"] },
              delivery_quantity: { type: ["number", "null"] },
              service_period_start: { type: ["string", "null"] },
              service_period_end: { type: ["string", "null"] },
              confidence: { type: "number" }
            },
            required: [
              "line_number",
              "item_code",
              "description",
              "quantity",
              "unit_of_measure",
              "unit_price",
              "discount_percentage",
              "discount_amount",
              "tax_rate",
              "tax_amount",
              "line_subtotal",
              "line_total",
              "purchase_order_number",
              "purchase_order_line_number",
              "delivery_quantity",
              "service_period_start",
              "service_period_end",
              "confidence"
            ]
          }
        }
      },
      required: [
        "classified_document_type",
        "document_number",
        "document_number_source",
        "document_date",
        "document_date_source",
        "purchase_order_number",
        "purchase_order_number_source",
        "purchase_order_numbers",
        "supplier_name",
        "supplier_registration_number",
        "supplier_vat_number",
        "supplier_vat_number_source",
        "supplier_is_vat_vendor",
        "supplier_country",
        "customer_name",
        "customer_registration_number",
        "customer_vat_number",
        "customer_vat_number_source",
        "customer_country",
        "currency",
        "subtotal",
        "discount_total",
        "tax_total",
        "shipping_total",
        "other_charges_total",
        "total_amount",
        "received_by",
        "received_date",
        "signature_present",
        "stamp_present",
        "line_items"
      ]
    },
    confidence: { type: "number" }
  },
  required: [
    "document_type_detected",
    "is_document_type_match",
    "extraction_status",
    "fields",
    "confidence"
  ]
};
